In [1]:
import torch

In [2]:
print(f"torch version: {torch.__version__}")

torch version: 2.4.1


In [3]:
a1 = torch.empty(1)
print(a1)

tensor([0.])


In [5]:
a2 = torch.empty(2)
print(a2)

tensor([0., 0.])


In [6]:
a3 = torch.empty(2, 3)
print(a3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
a4 = torch.rand(2, 2)
print(a4)

tensor([[0.0099, 0.2755],
        [0.5480, 0.1122]])


In [11]:
a5 = torch.zeros(3)
print(a5)

tensor([0., 0., 0.])


In [14]:
a7 = torch.ones(3)
print(a7)

tensor([1., 1., 1.])


In [15]:
a1 = torch.ones(2, 3)
print(a1)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [17]:
a1.size()

torch.Size([2, 3])

In [21]:
a1.shape

torch.Size([2, 3])

In [22]:
a1.dtype

torch.float32

In [23]:
a2 = torch.ones(2, 3, dtype=torch.float16)

In [24]:
a2.dtype

torch.float16

In [25]:
l1 = [23, 45, 67]
a3 = torch.tensor(l1)

In [27]:
a3.shape

torch.Size([3])

In [35]:
l2= [1, 3.9, 5]
a4 = torch.tensor(l2, dtype=torch.int)
a4.shape

torch.Size([3])

In [36]:
a4.dtype

torch.int32

In [37]:
a4

tensor([1, 3, 5], dtype=torch.int32)

In [39]:
L = [1, 2, 3, 4, 5]
a5 = torch.tensor(L, requires_grad=True, dtype=torch.float32)

In [40]:
a5

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [41]:
a1 = torch.ones(3)
a2 = torch.zeros(3)

b= a1 + a2 
c = 2 * a1

In [43]:
print(a1)
print(a2)
print(b)
print(c)

tensor([1., 1., 1.])
tensor([0., 0., 0.])
tensor([1., 1., 1.])
tensor([2., 2., 2.])


In [44]:
c.add_(a1)
print(c)

tensor([3., 3., 3.])


In [45]:
a3 = torch.rand(5, 5)
print(a3)

tensor([[0.6139, 0.7828, 0.9920, 0.2115, 0.1632],
        [0.8765, 0.9276, 0.3225, 0.7463, 0.6707],
        [0.2085, 0.4434, 0.5575, 0.9098, 0.5997],
        [0.7493, 0.9207, 0.9347, 0.5103, 0.0998],
        [0.5526, 0.2306, 0.1641, 0.2216, 0.7709]])


In [46]:
a3[:, 0]

tensor([0.6139, 0.8765, 0.2085, 0.7493, 0.5526])

In [47]:
A =torch.rand(5)
print(A)

B= A.numpy()
print(B)
print(type(B))

tensor([0.1421, 0.0403, 0.4708, 0.4063, 0.2667])
[0.14212424 0.04033643 0.47081155 0.40625846 0.26673263]
<class 'numpy.ndarray'>


In [50]:
B[0] = 9
print(A)

tensor([9.0000, 0.0403, 0.4708, 0.4063, 0.2667])


In [52]:
import numpy as np
A = np.ones(5)
B = torch.from_numpy(A)
print(A)
print(B)
print(type(B))

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
<class 'torch.Tensor'>
