In [29]:
import mlx.core as mx


In [30]:
# Linear Regression Using the Normal Equation
def linear_regression_normal_equation(X: mx.array, y: mx.array) -> mx.array:
    return mx.linalg.inv(X.T @ X , stream=mx.cpu) @ X.T @ y
# Test the function
X = mx.array([[1, 1], [1, 2], [1, 3]], dtype=mx.float32)
y = mx.array([1, 2, 3], dtype=mx.float32)
linear_regression_normal_equation(X, y)

array([9.53674e-07, 0.999999], dtype=float32)

In [31]:
# Linear Regression Using Gradient Descent
def linear_regression_gradient_descent(X: mx.array, y: mx.array, alpha: mx.float32 = 0.1, n_iterations: mx.int32 = 10000, seed: mx.int32 = 0) -> mx.array:
    # Initialize theta at random
    key = mx.random.key(seed)
    theta = mx.random.uniform(key=key, shape =(X.shape[1], 1), dtype=mx.float32)
    for _ in range(n_iterations):
        y_pred = X @ theta
        error = y_pred - y.reshape(-1, 1)
        gradient = X.T @ error / X.shape[0]
        theta = theta - alpha * gradient
    return theta
# Test the function
X = mx.array([[1, 1], [1, 2], [1, 3]] , dtype=mx.float32)
y = mx.array([1, 2, 3] , dtype=mx.float32)
linear_regression_gradient_descent(X, y)

array([[5.96017e-07],
       [1]], dtype=float32)

In [32]:
# Feature Scaling Implementation 
def feature_scaling(X: mx.array) -> [mx.array, mx.array]:
    # Standardization
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    standardized_data = (X - mean) / std
    
    # Min-Max Normalization
    min_value = X.min(axis=0)
    max_value = X.max(axis=0)
    normalized_data = (X - min_value) / (max_value - min_value)
    
    return standardized_data, normalized_data
    
# Test the function
X = mx.array([[1, 2], [3, 4], [5, 6]] , dtype=mx.float32)
feature_scaling(X)

(array([[-1.22474, -1.22474],
        [0, 0],
        [1.22474, 1.22474]], dtype=float32),
 array([[0, 0],
        [0.5, 0.5],
        [1, 1]], dtype=float32))

In [33]:
# Random Shuffle of Dataset
def shuffle_data(X: mx.array, y: mx.array) -> [mx.array, mx.array]:
    perm = mx.random.permutation(X.shape[0])
    return X[perm], y[perm]
# Test the function
X = mx.array([[1, 2], [3, 4], [5, 6]] , dtype=mx.float32)
y = mx.array([1, 2, 3] , dtype=mx.float32)
shuffle_data(X, y)

(array([[3, 4],
        [5, 6],
        [1, 2]], dtype=float32),
 array([2, 3, 1], dtype=float32))

In [34]:
# Batch Iterator for Dataset
def batch_iterator(X: mx.array, y: mx.array, batch_size: mx.int32 = 32) -> [mx.array, mx.array]:
    n_samples = X.shape[0]
    for i in range(0, n_samples, batch_size):
        yield X[i:i+batch_size], y[i:i+batch_size]
        
# Test the function
X = mx.array([[1, 2],
               [3, 4],
               [5, 6],
               [7, 8],
               [9, 10]] , dtype=mx.float32)
y = mx.array([1, 2, 3, 4, 5] , dtype=mx.float32)
batch_gen = batch_iterator(X, y, 2)

for batch_X, batch_y in batch_gen:
    print("Batch X:\n", batch_X)
    print("Batch y:\n", batch_y)

Batch X:
 array([[1, 2],
       [3, 4]], dtype=float32)
Batch y:
 array([1, 2], dtype=float32)
Batch X:
 array([[5, 6],
       [7, 8]], dtype=float32)
Batch y:
 array([3, 4], dtype=float32)
Batch X:
 array([[9, 10]], dtype=float32)
Batch y:
 array([5], dtype=float32)


In [36]:
# One-Hot Encoding of Nominal Values
def to_categorical(X: mx.array, n_classes: mx.int32) -> mx.array:
    one_hot = mx.zeros((X.size, n_classes))
    for i in range(X.size):
        one_hot[i, X[i]] = 1
    return one_hot
# Test the function
X = mx.array([0, 1, 2, 1, 0])
to_categorical(X, 3)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]], dtype=float32)

In [39]:
# Calculate Accuracy Score
def accuracy_score(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    true_predictions = 0
    for i in range(y_true.size):
        if y_true[i] ==y_pred[i]:
            true_predictions += 1
    return true_predictions / y_true.size
# Test the function
y_true = mx.array([1, 0, 1, 1, 0, 1])
y_pred = mx.array([1, 0, 0, 1, 0, 1])
accuracy_score(y_true, y_pred)

0.8333333333333334

In [40]:
# Implement Ridge Regression Loss Function
def ridge_loss(X: mx.array, w: mx.array, y_true: mx.array, alpha: mx.float32) -> mx.float32:
   return mx.mean((X @ w - y_true) ** 2) + alpha * mx.sum(w ** 2)
# Test the function
X = mx.array([[1, 1], [2, 1], [3, 1], [4, 1]], dtype=mx.float32)
w = mx.array([0.2, 2], dtype=mx.float32)
y_true = mx.array([2, 3, 4, 5], dtype=mx.float32)
alpha = 0.1
ridge_loss(X, w, y_true, alpha)

array(2.204, dtype=float32)

In [41]:
# Linear Kernel Function
def kernel_function(X1: mx.array, X2: mx.array) -> mx.float32:
    return mx.inner(X1, X2)
# Test the function
X1 = mx.array([1, 2, 3], dtype=mx.float32)
X2 = mx.array([4, 5, 6], dtype=mx.float32)
kernel_function(X1, X2)

array(32, dtype=float32)

In [42]:
# Implement Precision Metric
def precision(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    true_positives = 0
    false_positives = 0
    for i in range(y_true.size):
        if y_true[i] == 1 and y_pred[i] == 1:
            true_positives += 1
        elif y_true[i] == 0 and y_pred[i] == 1:
            false_positives += 1
    return true_positives / (true_positives + false_positives)
# Test the function
y_true = mx.array([1, 0, 1, 1, 0, 1], dtype=mx.float32)
y_pred = mx.array([1, 0, 1, 0, 0, 1], dtype=mx.float32)
precision(y_true, y_pred)

1.0

In [43]:
# Implement Recall Metric in Binary Classification
def recall(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    true_positives = 0
    false_negatives = 0
    for i in range(y_true.size):
        if y_true[i] == 1 and y_pred[i] == 1:
            true_positives += 1
        elif y_true[i] == 1 and y_pred[i] == 0:
            false_negatives += 1
    return true_positives / (true_positives + false_negatives)
# Test the function
y_true = mx.array([1, 0, 1, 1, 0, 1], dtype=mx.float32)
y_pred = mx.array([1, 0, 1, 0, 0, 1], dtype=mx.float32)
recall(y_true, y_pred)

0.75

In [44]:
# Implement F-Score Calculation for Binary Classification
def f_score(y_true: mx.array, y_pred: mx.array, beta: mx.float32 = 1) -> mx.float32:
    p = precision(y_true, y_pred)
    r = recall(y_true, y_pred)
    return (1 + beta ** 2) * (p * r) / ((beta ** 2) * p + r)
# Test the function
y_true = mx.array([1, 0, 1, 1, 0, 1], dtype=mx.float32)
y_pred = mx.array([1, 0, 1, 0, 0, 1], dtype=mx.float32)
f_score(y_true, y_pred)

0.8571428571428571

In [45]:
# Implement Gini Impurity Calculation for a Set of Classes
def gini_impurity(y: mx.array) -> mx.float32:
    bincount = mx.zeros(y.max() + 1)
    for i in range(y.size):
        bincount = bincount.at[y[i]].add(1)
    return 1 - mx.sum((bincount / y.size) ** 2)
# Test the function
y = mx.array([0, 1, 1, 1, 0])
gini_impurity(y)

array(0.48, dtype=float32)

In [46]:
# Calculate R-squared for Regression Analysis

def r_squared(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    ss_res = mx.sum((y_true - y_pred) ** 2)
    ss_tot = mx.sum((y_true - y_true.mean()) ** 2)
    return 1 - ss_res / ss_tot
# Test the function
y_true = mx.array([1, 2, 3, 4, 5])
y_pred = mx.array([1.1, 2.1, 2.9, 4.2, 4.8])
r_squared(y_true, y_pred)

array(0.989, dtype=float32)

In [47]:
# Calculate Root Mean Square Error (RMSE)
def rmse(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    return mx.sqrt(mx.mean((y_true - y_pred) ** 2))
# Test the function
y_true = mx.array([3, -0.5, 2, 7])
y_pred = mx.array([2.5, 0.0, 2, 8])
rmse(y_true, y_pred)

array(0.612372, dtype=float32)

In [48]:
# Calculate Jaccard Index for Binary Classification
def jaccard_index(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    intersection = 0
    union = 0
    for i in range(y_true.size):
        if y_true[i] == 1 and y_pred[i] == 1:
            intersection += 1
        if y_true[i] == 1 or y_pred[i] == 1:
            union += 1
    result = intersection / union
    if mx.isnan(result):
        return  0.0
    return intersection / union
y_true = mx.array([1, 0, 1, 1, 0, 1])
y_pred = mx.array([1, 0, 1, 0, 0, 1])
jaccard_index(y_true, y_pred)

0.75

In [49]:
# Calculate Dice Score for Classification
def dice_score(y_true: mx.array, y_pred: mx.array) -> mx.float32:
    true_positives = 0
    false_positives = 0
    false_negatives = 0
    for i in range(y_true.size):
        if y_true[i] == 1 and y_pred[i] == 1:
            true_positives += 1
        elif y_true[i] == 0 and y_pred[i] == 1:
            false_positives += 1
        elif y_true[i] == 1 and y_pred[i] == 0:
            false_negatives += 1
   
    if y_true.sum() == 0 and y_pred.sum() == 0:
        return 0.0
    return 2 * true_positives / (2 * true_positives + false_positives + false_negatives)
# Test the function
y_true = mx.array([1, 1, 0, 1, 0, 1])
y_pred = mx.array([1, 1, 0, 0, 0, 1])
dice_score(y_true, y_pred)

0.8571428571428571

In [50]:
# Generate a Confusion Matrix for Binary Classification
def confusion_matrix(data: mx.array) -> mx.array:
    tp, fp, fn, tn = 0, 0, 0, 0
    for i in range(data.shape[0]):
        if data[i, 0] == 1 and data[i, 1] == 1:
            tp += 1
        elif data[i, 0] == 1 and data[i, 1] == 0:
            fp += 1
        elif data[i, 0] == 0 and data[i, 1] == 1:
            fn += 1
        elif data[i, 0] == 0 and data[i, 1] == 0:
            tn += 1
    conf_matrix = mx.array([[tp, fp], [fn, tn]])
    return conf_matrix
# Test the function
data = mx.array([[1, 1], [1, 0], [0, 1], [0, 0], [0, 1]])
confusion_matrix(data)

array([[1, 1],
       [2, 1]], dtype=int32)